[package]
name = "genesis_brain"
version = "0.1.0"
edition = "2021"

[dependencies]
genulse_core = { path = "../genulse_core" }
genesis_togenizer = { path = "../genesis_togenizer" }
log = "0.4"
env_logger = "0.10"
